import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Workout planning LLM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const { push } = useRouter();

  // if (localStorage.getItem("user")) {
  //   push("/planning");
  // } else {
  //   push("/");
  // }

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen">
          <div className="m-auto">
            <div className="">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
